namespace MythicDuel.Core.Models;

public sealed class GameMetrics
{
    public required string GameId { get; init; }
    public int Seed { get; set; }
    public string Winner { get; set; } = string.Empty;
    public string Loser { get; set; } = string.Empty;
    public bool Timeout { get; set; }
    public string EndReason { get; set; } = string.Empty;
    public string Outcome { get; set; } = string.Empty;
    public string AdjudicatedWinner { get; set; } = string.Empty;
    public int TimeoutDraws { get; set; }
    public int TimeoutAdjudicatedRed { get; set; }
    public int TimeoutAdjudicatedIron { get; set; }
    public int TurnCount { get; set; }
    public int PhaseCount { get; set; }
    public int FinalRedShrinesBroken { get; set; }
    public int FinalIronShrinesBroken { get; set; }
    public int? FirstShrineDamageTurn { get; set; }
    public int? FirstShrineBreakTurn { get; set; }
    public int? FirstRedShrineBreakTurn { get; set; }
    public int? FirstIronShrineBreakTurn { get; set; }
    public int? FirstAncestorAwakenedTurn { get; set; }
    public int? FirstL2Turn { get; set; }
    public int? FirstL3Turn { get; set; }
    public int RedL2Played { get; set; }
    public int RedL2EnteredBattlefield { get; set; }
    public int RedL2Evolved { get; set; }
    public int RedL2HardCast { get; set; }
    public int RedL3Played { get; set; }
    public int RedL3EnteredBattlefield { get; set; }
    public int RedL3Evolved { get; set; }
    public int RedL3HardCast { get; set; }
    public int RedL3Recalled { get; set; }
    public int RedL3PlayerWon { get; set; }
    public int IronL2Played { get; set; }
    public int IronL2EnteredBattlefield { get; set; }
    public int IronL2Evolved { get; set; }
    public int IronL2HardCast { get; set; }
    public int IronL3Played { get; set; }
    public int IronL3EnteredBattlefield { get; set; }
    public int IronL3Evolved { get; set; }
    public int IronL3HardCast { get; set; }
    public int IronL3Recalled { get; set; }
    public int IronL3PlayerWon { get; set; }
    public int FailedEvolutionAttemptsRed { get; set; }
    public int FailedEvolutionAttemptsIron { get; set; }
    public int LegalEvolveActionsGeneratedRed { get; set; }
    public int LegalEvolveActionsGeneratedIron { get; set; }
    public int LegalL2EvolveActionsGeneratedRed { get; set; }
    public int LegalL3EvolveActionsGeneratedRed { get; set; }
    public int LegalL2EvolveActionsGeneratedIron { get; set; }
    public int LegalL3EvolveActionsGeneratedIron { get; set; }
    public int EvolveActionsChosenRed { get; set; }
    public int EvolveActionsChosenIron { get; set; }
    public int EvolveWindowsRed { get; set; }
    public int EvolveWindowsIron { get; set; }
    public int TurnsWithLegalL2EvolutionRed { get; set; }
    public int TurnsWithLegalL3EvolutionRed { get; set; }
    public int TurnsWithLegalL2EvolutionIron { get; set; }
    public int TurnsWithLegalL3EvolutionIron { get; set; }
    public int HardCastChosenWhileLegalEvolveActionExistsRed { get; set; }
    public int HardCastChosenWhileLegalEvolveActionExistsIron { get; set; }
    public int HardCastChosenWhileEvolutionBaseExistsRed { get; set; }
    public int HardCastChosenWhileEvolutionBaseExistsIron { get; set; }
    public int LegalAwakenActionsGeneratedRed { get; set; }
    public int LegalAwakenActionsGeneratedIron { get; set; }
    public int AwakenActionsChosenRed { get; set; }
    public int AwakenActionsChosenIron { get; set; }
    public int AwakenActionsSkippedWhileLegalRed { get; set; }
    public int AwakenActionsSkippedWhileLegalIron { get; set; }
    public int AncestorSwitchesRed { get; set; }
    public int AncestorSwitchesIron { get; set; }
    public int MemorySpentOnAncestorsRed { get; set; }
    public int MemorySpentOnAncestorsIron { get; set; }
    public string FirstAwakenedAncestorRed { get; set; } = string.Empty;
    public string FirstAwakenedAncestorIron { get; set; } = string.Empty;
    public int TurnsWithAwakenedAncestorRed { get; set; }
    public int TurnsWithAwakenedAncestorIron { get; set; }
    public int FirstHunterBonusDamage { get; set; }
    public int GrandmotherHealingDone { get; set; }
    public int ChildDrawDiscardTriggers { get; set; }
    public int IronHyenaAncestorBonusDamage { get; set; }
    public int SmithOfferingDiscountSaved { get; set; }
    public int ToothMotherBonusDamage { get; set; }
    public int MemoryGeneratedRed { get; set; }
    public int MemorySpentRed { get; set; }
    public int MemoryEndRed { get; set; }
    public int MemoryGeneratedIron { get; set; }
    public int MemorySpentIron { get; set; }
    public int MemoryEndIron { get; set; }
    public int OfferingsSpentRed { get; set; }
    public int OfferingsSpentIron { get; set; }
    public int AttacksDeclaredRed { get; set; }
    public int AttacksDeclaredIron { get; set; }
    public int PackUnitsReadyAtCombatStartRed { get; set; }
    public int PackUnitsReadyAtCombatStartIron { get; set; }
    public int PackAssaultSlotsGeneratedRed { get; set; }
    public int PackAssaultSlotsGeneratedIron { get; set; }
    public int PackAssaultSlotsAvailableRed { get; set; }
    public int PackAssaultSlotsAvailableIron { get; set; }
    public int PackAssaultSlotsSkippedRed { get; set; }
    public int PackAssaultSlotsSkippedIron { get; set; }
    public int TurnsWithPackBonusRed { get; set; }
    public int TurnsWithPackBonusIron { get; set; }
    public int MaxAttacksAvailableThisCombatRed { get; set; }
    public int MaxAttacksAvailableThisCombatIron { get; set; }
    public int AttacksPreventedByAssaultLimitRed { get; set; }
    public int AttacksPreventedByAssaultLimitIron { get; set; }
    public int StandardAssaultSlotsSpentRed { get; set; }
    public int StandardAssaultSlotsSpentIron { get; set; }
    public int PackAssaultSlotsSpentRed { get; set; }
    public int PackAssaultSlotsSpentIron { get; set; }
    public int ShrineAttacksRed { get; set; }
    public int ShrineAttacksIron { get; set; }
    public int BlockedShrineAttacksRed { get; set; }
    public int BlockedShrineAttacksIron { get; set; }
    public int LegalBlockOptionsRed { get; set; }
    public int LegalBlockOptionsIron { get; set; }
    public int BlocksChosenRed { get; set; }
    public int BlocksChosenIron { get; set; }
    public int BlocksDeclinedRed { get; set; }
    public int BlocksDeclinedIron { get; set; }
    public int UnitsKilledRed { get; set; }
    public int UnitsKilledIron { get; set; }
    public int SpiritsDispersedRed { get; set; }
    public int SpiritsDispersedIron { get; set; }
    public int WoundedEventsRed { get; set; }
    public int WoundedEventsIron { get; set; }
    public int WoundedDamageReductionEventsRed { get; set; }
    public int WoundedDamageReductionEventsIron { get; set; }
    public int PierceOverflowEventsRed { get; set; }
    public int PierceOverflowEventsIron { get; set; }
    public int PierceOverflowDamageRed { get; set; }
    public int PierceOverflowDamageIron { get; set; }
    public int WeaponmasterPierceEvents { get; set; }
    public int SoulslayerPierceEvents { get; set; }
    public int LeopardHunterPierceEvents { get; set; }
    public int PreparedTacticsPreparedRed { get; set; }
    public int PreparedTacticsPreparedIron { get; set; }
    public int PreparedTacticsTriggeredRed { get; set; }
    public int PreparedTacticsTriggeredIron { get; set; }
    public int PreparedTacticsExpiredRed { get; set; }
    public int PreparedTacticsExpiredIron { get; set; }
    public int ForgottenCardsRed { get; set; }
    public int ForgottenCardsIron { get; set; }
    public int FadeCardsResolvedRed { get; set; }
    public int FadeCardsResolvedIron { get; set; }
    public int FadeTacticsTriggeredRed { get; set; }
    public int FadeTacticsTriggeredIron { get; set; }
    public int FadeTacticsExpiredRed { get; set; }
    public int FadeTacticsExpiredIron { get; set; }
    public int CardsDrawnRed { get; set; }
    public int CardsDrawnIron { get; set; }
    public int CardsRetainedRed { get; set; }
    public int CardsRetainedIron { get; set; }
    public int CardsDiscardedRed { get; set; }
    public int CardsDiscardedIron { get; set; }
    public int DeckReshufflesRed { get; set; }
    public int DeckReshufflesIron { get; set; }
    public int ForgottenCardsExcludedFromReshuffleRed { get; set; }
    public int ForgottenCardsExcludedFromReshuffleIron { get; set; }
    public int PresenceUsedRed { get; set; }
    public int PresenceUsedIron { get; set; }
    public int PresenceLimitRed { get; set; }
    public int PresenceLimitIron { get; set; }
    public int PhaseBoundaryDoubleTurnsRed { get; set; }
    public int PhaseBoundaryDoubleTurnsIron { get; set; }
    public int ShrinesBrokenOnPhaseBoundaryRed { get; set; }
    public int ShrinesBrokenOnPhaseBoundaryIron { get; set; }
    public int EvolutionsOnPhaseBoundaryRed { get; set; }
    public int EvolutionsOnPhaseBoundaryIron { get; set; }
    
    // Seat and Phase Reversal diagnostics
    public int? FirstShrineDamageTurnRed { get; set; }
    public int? FirstShrineDamageTurnIron { get; set; }
    public int WinsInOddPhase { get; set; }
    public int WinnerWasFirstPlayerInFinalPhase { get; set; }
    public int ShrineDamageDealtDuringDoubleTurnRed { get; set; }
    public int ShrineDamageDealtDuringDoubleTurnIron { get; set; }
}
